### ISSUE TITLE
Select Single issue with upper case formatting (was: ... with host variables)

### ISSUE THREAD

**Issue by fidley** [lc-leuc/ABAPQuickFixS4Conversion#2]
![selectSingle issue](https://user-images.githubusercontent.com/7912195/178254867-a27048b6-dc91-47d0-888c-1ec9ee160baf.gif)

**Comment by lc-leuc** [comment]
Thanks Łukasz,

the issue is cased by the upper case formatting.
Please, if you like, check out the new version 1.2.2.
