### ISSUE TITLE
SelectNewStyle wrongly puts @ infront of TABLE for INTO TABLE

### ISSUE THREAD

**Issue by kevinholtkamp** [lc-leuc/ABAPQuickFixS4Conversion#4]
The following code:
![image](https://user-images.githubusercontent.com/32170328/191249316-a290ea6d-6c95-488b-a85b-68920e2b9f5d.png)

turns into this:
![image](https://user-images.githubusercontent.com/32170328/191249390-f4a7905d-8e23-4c7d-a181-af2dc8c2ddc0.png)

when applying the quick fix to convert to the new SQL style.

In the following case I get the error message that "mtart is not an internal table", so I think we can assume that whenever TABLE is specified after INTO, it is not a variable.
![image](https://user-images.githubusercontent.com/32170328/191250425-6dad8224-f433-4469-9ba5-6294b8067a1c.png)

**Comment by lc-leuc** [comment]
Fixed with version 1.4.0 fa160da7ff9804783f344aed4fa1583dd2d2cc5b

```abap
    "" #4 before qf
    select * from mara into table tmara where mtart = 'FERT'.
    "" #4 after qf
    select *
      from mara
      into table @tmara
      where mtart = 'FERT'.
```

```abap
    "" #4 before
    select matnr mtart
      from mara
      into table mtart
      where mtart = 'FERT'.
    "" #4 after
    select matnr, mtart
      from mara
      into table @mtart
      where mtart = 'FERT'.
```

Thank you for reporting.
